# Question 1

## Arrays

https://www.hackerrank.com/challenges/np-arrays/problem

In [2]:
import numpy as np

In [4]:
def arrays(arr):
    numpy_array = np.array(arr)
    float_array = numpy_array.astype(np.float)
    reversed_array = float_array[::-1]
    return reversed_array
    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Question 2

## Shape and Reshape

https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [7]:
arr = input().strip().split(' ')

my_array = np.array([arr]).astype(np.int)
array_3d = np.reshape(my_array, (3,3))
print(array_3d)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 3

## Transpose and Flatten

https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem

In [41]:
n,m = map(int, input().split(' '))
arr = []
for i in range(n):
    arr.extend(list(map(int, input().split(' '))))
my_array = np.array(arr).reshape(n,m)
print(my_array.transpose())
print(my_array.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Question 4

## Concatenate

https://www.hackerrank.com/challenges/np-concatenate/problem

In [46]:
n,m,p = map(int, input().split(' '))
arr_1 = []
arr_2 = []
for i in range(n):
    arr_1.extend(list(map(int, input().split(' '))))

for j in range(m):
    arr_2.extend(list(map(int, input().split(' '))))
    
my_array_1 = np.array(arr_1).reshape(n,p)
my_array_2 = np.array(arr_2).reshape(m,p)

print(np.concatenate((my_array_1, my_array_2)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Question 5

## Zeros and Ones

https://www.hackerrank.com/challenges/np-zeros-and-ones/problem

In [48]:
ss_integers= list(map(int, input().split(' ')))
print(np.zeros((ss_integers)).astype(np.int))
print(np.ones((ss_integers)).astype(np.int))

4 4 4
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# Question 6

## Eye and Identify

https://www.hackerrank.com/challenges/np-eye-and-identity/problem

In [52]:
n,m = map(int, input().split(' '))
print(np.eye(n,m))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 7

## Array Mathematics

https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [58]:
n,m = map(int, input().split(' '))
arr_1 = []
arr_2 = []
for i in range(n):
    arr_1.extend(list(map(int, input().split(' '))))

for j in range(n):
    arr_2.extend(list(map(int, input().split(' '))))
    
a = np.array(arr_1).reshape(n,m)
b = np.array(arr_2).reshape(n,m)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Question 8

## Floor, Ceil and Rint

https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem

In [61]:
A = np.array(list(input().split(' ')), float)
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


# Question 9

## Sum and Prod

https://www.hackerrank.com/challenges/np-sum-and-prod/problem

In [63]:
n,m = map(int, input().split(' '))
arr = []
for i in range(n):
    arr.extend(list(map(int, input().split(' '))))
    
my_prod_array = np.array(arr).reshape(n,m)

arr_prod = 1

for i in range(len(np.sum(my_prod_array, axis = 0))):
    arr_prod *= (np.sum(my_prod_array, axis = 0)[i])
    
print(arr_prod)

2 2
1 2
3 4
24


# Question 10

## Min and Max

https://www.hackerrank.com/challenges/np-min-and-max/problem

In [66]:
n,m = map(int, input().split(' '))
arr = []
for i in range(n):
    arr.extend(list(map(int, input().split(' '))))
    
my_max_array = np.array(arr).reshape(n,m)
print(my_max_array)

my_min_array = np.min(my_max_array,axis = 1)
print(my_min_array)
my_max_min_array = np.max(my_min_array)
print(my_max_min_array)

4 2
3 5
3 7
1 3
4 0
[[3 5]
 [3 7]
 [1 3]
 [4 0]]
[3 3 1 0]
3


# Question 11

## Mean,Var, and Std

https://www.hackerrank.com/challenges/np-mean-var-and-std/problem

In [67]:
n,m = map(int, input().split(' '))
arr = []
for i in range(n):
    arr.extend(list(map(int, input().split(' '))))
    
My_arr = np.array(arr).reshape(n,m)
print(My_arr)
print(np.mean(My_arr, axis = 1))
print(np.var(My_arr, axis = 0))
print(np.std(My_arr, axis = None))

2 2
1 2
3 4
[[1 2]
 [3 4]]
[1.5 3.5]
[1. 1.]
1.118033988749895


# Question 12

## Dot and Cross

https://www.hackerrank.com/challenges/np-dot-and-cross/problem

In [70]:
n = int(input())
arr_A = []
arr_B = []

for i in range(n):
    arr_A.extend(list(map(int, input().split(' '))))
    
for j in range(n):
    arr_B.extend(list(map(int, input().split(' '))))
    
A = np.array(arr_A).reshape(n,n)
B = np.array(arr_B).reshape(n,n)

print(np.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Question 13

## Inner and Outer

https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [71]:
A = np.array(input().split(),int)
B = np.array(input().split(),int)
print(np.inner(A,B),np.outer(A,B), sep = "\n")

0 1
2 3
3
[[0 0]
 [2 3]]


# Question 14

## Polynomials

https://www.hackerrank.com/challenges/np-polynomials/problem

In [72]:
print(np.poly([-1, 1, 1, 10]))

[  1. -11.   9.  11. -10.]


In [74]:
P = list(map(float,input().split()))
x = int(input())
print(np.polyval(P,x))

1.1 2 3
0
3.0


# Question 15

## Linear Alzebra

https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [77]:
import numpy as np

n = int(input())
arr = []
for i in range(n):
    arr.extend(list(map(float,input().split())))
A = np.array(arr).reshape(n,n)
print(round(np.linalg.det(A),2))


2
1.1 1.1
1.1 1.2
0.11
